version: "2"

run:
  go: "1.25.0"
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: false
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings

    staticcheck:
      checks:
        - all
        - -QF*
        - -ST1000

formatters:
  enable:
    - gci
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/Southclaws/sampctl)
