project_name: sampctl
release:
  github:
    owner: Southclaws
    name: sampctl
builds:
  - binary: sampctl
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - "386"
      - "amd64"
    env:
      - CGO_ENABLED=0
    ldflags:
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.segmentKey={{.Env.SEGMENT_KEY}}
archive:
  format: tar.gz
  name_template:
    "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
dockers:
  - image: southclaws/sampctl
    goos: linux
    goarch: "386"
    binary: sampctl
    dockerfile: Dockerfile
    latest: true
nfpm:
  vendor: Southclaws
  homepage: https://github.com/Southclaws/sampctl
  maintainer: Southclaws <hello@southcla.ws>
  description:
    The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer.
  license: GPLv3
  formats:
    - deb
    - rpm
brew:
  github:
    owner: Southclaws
    name: homebrew-sampctl
  homepage: https://github.com/Southclaws/sampctl
  description:
    The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer.
scoop:
  bucket:
    owner: Southclaws
    name: scoops
  homepage: http://sampctl.com
  description:
    The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer.
  license: GPLv3
