version: 2
project_name: sampctl

builds:
  - binary: sampctl
    main: ./src
    goos:
      - windows
      - linux
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X main.version={{ .Version }}"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*

snapshot:
  version_template: "{{ .Commit }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

nfpms:
  - id: packages
    vendor: Southclaws
    homepage: https://github.com/Southclaws/sampctl
    maintainer: Southclaws <hello@southcla.ws>
    description: The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer.
    license: GPLv3
    formats:
      - deb
      - rpm

homebrew_casks:
  - name: sampctl
    repository:
      owner: Southclaws
      name: sampctl
    homepage: https://github.com/Southclaws/sampctl
    description: The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer.

scoops:
  - repository:
      owner: Southclaws
      name: sampctl
    homepage: http://sampctl.com
    description: The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer.
    license: GPLv3
