FROM ubuntu
WORKDIR /samp
RUN mkdir samp && \
    dpkg --add-architecture i386 && \
    apt update && \
    apt install -y g++-multilib git ca-certificates
COPY sampctl /bin/sampctl
ENTRYPOINT ["sampctl"]
