# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sampctl < Formula
  desc "The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer."
  homepage "https://github.com/Southclaws/sampctl"
  version "1.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Southclaws/sampctl/releases/download/1.11.0/sampctl_1.11.0_darwin_amd64.tar.gz"
      sha256 "1633f8e7acc748734f04c51f49c1452b1a27ca22e3a4bd29d06b942c65a37633"

      def install
        bin.install "sampctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Southclaws/sampctl/releases/download/1.11.0/sampctl_1.11.0_linux_amd64.tar.gz"
      sha256 "194c4e2ee2bd21384460e8a72df739886f89edb088f4df216699a5b88d914c26"

      def install
        bin.install "sampctl"
      end
    end
  end
end
