version: 3

vars:
  VERSION: { sh: "git describe --tags --dirty --always" }
  LDFLAGS: -ldflags "-X main.version={{.VERSION}}"
  GITHUB_TOKEN: { sh: "echo $GITHUB_TOKEN" }
  PATH: { sh: "pwd" }

tasks:
  # Default task should clean up and build a static version of sampctl
  default:
    deps: ["clean", "static"]

  # Build static version of sampctl
  static:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -a {{.LDFLAGS}} -o sampctl ./src

  # Build a fast non static version
  fast:
    cmds:
      - go build {{.LDFLAGS}} -o sampctl ./src

  # Install sampctl into the go bin folder
  install:
    cmds:
      - go install {{.LDFLAGS}} ./src

  # Remove sampctl binary
  clean:
    cmds:
      - rm -f ./sampctl

  # Run go test against source code
  test:
    cmds:
      - go test --race -v ./src/...

  # Releasing sampctl via goreleaser
  # for osx tar fix
  # https://github.com/goreleaser/goreleaser/issues/409
  release:
    cmds:
      - <<
        PATH="/usr/local/opt/gnu-tar/libexec/gnubin:{{.PATH}}"
        GITHUB_TOKEN={{.GITHUB_TOKEN}}
        goreleaser
        --snapshot
        --rm-dist

  # Generating documentation via docgen
  docs:
    deps: ["fast"]
    cmds:
      - ./scripts/docgen.sh

  # Building the sampctl docker image
  docker:build:
    cmds:
      - docker build -t southclaws/sampctl:{{.VERSION}} .

  # Building and pushing the sampctl docker image
  docker:push:
    deps: ["docker:build"]
    cmds:
      - docker push southclaws/sampctl:{{.VERSION}}

  # Creates a docker enviornment with ubuntu to test sampctl functionality
  env:ubuntu:
    cmds:
      - docker run -it -v{{.PATH}}:/sampctl ubuntu

  # Creates a docker enviornment with centos to test sampctl functionality
  env:centos:
    cmds:
      - docker run -it -v{{.PATH}}:/sampctl centos

  earthly:test:
    cmds:
      - earthly +test

  earthly:build:
    cmds:
      - earthly +build

  earthly:build-windows:
    cmds:
      - earthly +build-windows

  earthly:build-all:
    cmds:
      - earthly +build-all

  earthly:all:
    cmds:
      - earthly +all

  earthly:release:
    cmds:
      - earthly +release

  earthly:release-windows:
    cmds:
      - earthly +release-windows

  earthly:release-all:
    cmds:
      - earthly +release-all

  ci:build:
    desc: "Build sampctl binaries for both Linux and Windows"
    cmds:
      - earthly +release-all

  ci:build-linux:
    desc: "Build sampctl binary for Linux only"
    cmds:
      - earthly +release

  ci:build-windows:
    desc: "Build sampctl binary for Windows only"
    cmds:
      - earthly +release-windows

  ci:test:
    desc: "Run tests with token"
    deps: ["ci:build"]
    cmds:
      - earthly --secret FULL_ACCESS_GITHUB_TOKEN +test

  ci:full:
    desc: "Run full CI workflow: build then test"
    cmds:
      - task: ci:build
      - task: ci:test
