# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sampctl < Formula
  desc "The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer."
  homepage "https://github.com/Southclaws/sampctl"
  version "1.12.0"

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Southclaws/sampctl/releases/download/1.12.0/sampctl_1.12.0_Linux_x86_64.tar.gz"
      sha256 "0ed15f1d1d874a86fc6973752ce1f0211c25e34436cc6e345cc14b9a51b464e9"

      def install
        bin.install "sampctl"
      end
    end
  end
end
