# This file was generated by GoReleaser. DO NOT EDIT.
cask "sampctl" do
  version "1.14.0"

  on_linux do
    on_intel do
      sha256 "62b5cd18f1969168f147b3e9595c300b902622b4a547b5dbd1b99c49dab8544d"
      url "https://github.com/Southclaws/sampctl/releases/download/#{version}/sampctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb1fb0dce72b1286e4421da702a2f36e31f905b99292a8b4a3631bbfc9c95210"
      url "https://github.com/Southclaws/sampctl/releases/download/#{version}/sampctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sampctl"
  desc "The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer."
  homepage "https://github.com/Southclaws/sampctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sampctl"

  # No zap stanza required

end
