# This file was generated by GoReleaser. DO NOT EDIT.
cask "sampctl" do
  version "1.14.1"

  on_linux do
    on_intel do
      sha256 "e759e9d71beec8204323c73b555faf0d151e9c5150993e78162b6ac9126e821f"
      url "https://github.com/Southclaws/sampctl/releases/download/#{version}/sampctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b748bd8393de3b1a49bc607cb12466b4645a1de6f35c020694b10a5914f35bb"
      url "https://github.com/Southclaws/sampctl/releases/download/#{version}/sampctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sampctl"
  desc "The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer."
  homepage "https://github.com/Southclaws/sampctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sampctl"

  # No zap stanza required

end
