package runtime

import (
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/pkg/errors"
	"golang.org/x/text/encoding/charmap"
	"golang.org/x/text/transform"

	"github.com/Southclaws/sampctl/src/pkg/infrastructure/print"
	run "github.com/Southclaws/sampctl/src/pkg/runtime/config"
)

type sampConfig struct {
	workingDir string
}

func newSAMPConfig(workingDir string) *sampConfig {
	return &sampConfig{workingDir: workingDir}
}

func (s *sampConfig) configFilename() string {
	return "server.cfg"
}

func (s *sampConfig) generate(cfg *run.Runtime) (err error) {
	configJSONPath := filepath.Join(s.workingDir, "config.json")
	if _, err := os.Stat(configJSONPath); err == nil {
		print.Verb("Removing existing config.json file (SA-MP uses server.cfg)")
		if removeErr := os.Remove(configJSONPath); removeErr != nil {
			return errors.Wrap(removeErr, "failed to remove stale config.json")
		}
	}

	file, err := os.Create(filepath.Join(s.workingDir, s.configFilename()))
	if err != nil {
		return err
	}
	defer closeConfigResource(&err, file, "failed to close server.cfg")

	encoder := charmap.Windows1252.NewEncoder()
	writer := transform.NewWriter(file, encoder)
	defer closeConfigResource(&err, writer, "failed to flush server.cfg")

	if err := adjustForOS(s.workingDir, cfg.Platform, cfg); err != nil {
		return err
	}

	if _, err = io.WriteString(writer, "echo loading server.cfg generated by sampctl - do not edit this file by hand.\n"); err != nil {
		return err
	}

	v := reflect.ValueOf(*cfg)
	t := reflect.TypeOf(*cfg)

	for i := 0; i < v.NumField(); i++ {
		fieldval := v.Field(i)
		stype := t.Field(i)

		if stype.Tag.Get("ignore") != "" {
			continue
		}

		required := stype.Tag.Get("required") == "1"
		nodefault := stype.Tag.Get("default") == ""
		if !required && nodefault && fieldval.IsNil() {
			continue
		}

		name := strings.Split(stype.Tag.Get("json"), ",")[0]
		if real := stype.Tag.Get("cfg"); real != "" {
			name = real
		}

		defaultValue := stype.Tag.Get("default")
		numbered := stype.Tag.Get("numbered") != ""

		line := ""

		switch stype.Type.String() {
		case "*string":
			line, err = fromString(name, fieldval, required, defaultValue)
		case "[]string":
			line, err = fromSlice(name, fieldval, required, numbered)
		case "[]run.Plugin":
			line, err = fromSlice(name, fieldval, required, numbered)
		case "*bool":
			line, err = fromBool(name, fieldval, required, defaultValue)
		case "*int":
			line, err = fromInt(name, fieldval, required, defaultValue)
		case "*float32":
			line, err = fromFloat(name, fieldval, required, defaultValue)
		case "map[string]string":
			line, err = fromMap(name, fieldval, required)
		default:
			err = errors.Errorf("unknown kind %q", stype.Type.String())
		}
		if err != nil {
			return errors.Wrapf(err, "failed to unpack settings object %s", name)
		}

		if _, err := io.WriteString(writer, line); err != nil {
			return errors.Wrap(err, "failed to write setting to server.cfg")
		}
	}

	return nil
}
